config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  resources :sessions
  resources :two_factor_auths
  resources :accounts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :device_id, :remote_ip, :request_id

  public :assign_attributes

  def device_id=(value)
    super
    NewRelic::Agent.add_custom_attributes(device_id: value)
  end

  def remote_ip=(value)
    super
    NewRelic::Agent.add_custom_attributes(remote_ip: value)
  end

  def request_id=(value)
    super
    NewRelic::Agent.add_custom_attributes(request_id: value)
  end
end

app/models/user.rb
class User < ApplicationRecord

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_custom_attributes

  def device_id
    cookies[:device_id] ||= { value: SecureRandom.uuid, expires: 10.years.from_now }
  end

  def custom_attributes
    { device_id: device_id,
      remote_ip: request.remote_ip,
      request_id: request.request_id
    }
  end

  def set_custom_attributes
    Current.assign_attributes(custom_attributes)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    authenticate_user = AuthenticateUser.new(params[:email], params[:password])

    if authenticate_user.call
      redirect_to  new_two_factor_auth_path
    else
      flash.now[:error] = 'invalid email/password combo'
      render :new
    end
  end
end

app/controllers/two_factor_auths_controller.rb
class TwoFactorAuthsController < ApplicationController
  def create
    if params[:code] == '1234'
      redirect_to accounts_path
    else
      flash.now['error'] = "incorrect code"
      render :new
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/index.erb
success!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MetricsDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/two_factor_auths/new.erb
<% if flash[:error].present? -%>
  <%= flash[:error] -%>
  <br /><br />
<% end -%>

<%= form_tag(two_factor_auths_path) do %>
  correct code: 1234
  <br />
  <%= label_tag(:code, "code") %>
  <%= text_field_tag(:code) %>
  <br /><br />
  <%= submit_tag %>
<% end %>